### ISSUE TITLE
Can't Build On Snow Leopard

### ISSUE THREAD

**Issue by grkpfl** [jbarnette/johnson#18]
Hello, Please help me:

$ sudo gem install johnson
Building native extensions.  This could take a while...
ERROR:  Error installing johnson:
    ERROR: Failed to build gem native extension.

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby extconf.rb
cat: ../../dist/Darwin_DBG.OBJ/nspr/Version: No such file or directory
cd editline; make -f Makefile.ref all
cc -o Darwin_DBG.OBJ/editline.o -c -Wall -Wno-format -MMD -DXP_UNIX -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root  -DJSFILE  -DANSI_ARROWS -DHAVE_TCGETATTR -DHIDE -DUSE_DIRENT -DSYS_UNIX -DHAVE_STDLIB -DUNIQUE_HISTORY editline.c
editline.c: In function ‘readline’:
editline.c:1038: warning: implicit declaration of function ‘getpid’
editline.c: In function ‘add_history’:
editline.c:1051: warning: pointer targets in passing argument 2 of ‘strcmp’ differ in signedness
cc -o Darwin_DBG.OBJ/sysunix.o -c -Wall -Wno-format -MMD -DXP_UNIX -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root  -DJSFILE  -DANSI_ARROWS -DHAVE_TCGETATTR -DHIDE -DUSE_DIRENT -DSYS_UNIX -DHAVE_STDLIB -DUNIQUE_HISTORY sysunix.c
ar rv Darwin_DBG.OBJ/libedit.a Darwin_DBG.OBJ/editline.o Darwin_DBG.OBJ/sysunix.o
r - Darwin_DBG.OBJ/editline.o
r - Darwin_DBG.OBJ/sysunix.o
ranlib Darwin_DBG.OBJ/libedit.a
make -f Makefile.ref  Darwin_DBG.OBJ/libjs.a Darwin_DBG.OBJ/libjs.dylib Darwin_DBG.OBJ/js  Darwin_DBG.OBJ/jsautocfg.h Darwin_DBG.OBJ/jscpucfg Darwin_DBG.OBJ/jscpucfg.o
cat: ../../dist/Darwin_DBG.OBJ/nspr/Version: No such file or directory
make[1]: Circular jscpucfg.h <- Darwin_DBG.OBJ/jsautocfg.h dependency dropped.
cc -o Darwin_DBG.OBJ/jscpucfg.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jscpucfg.c
cc -o Darwin_DBG.OBJ/jscpucfg Darwin_DBG.OBJ/jscpucfg.o
make[1]: Circular Darwin_DBG.OBJ/jsautocfg.h <- Darwin_DBG.OBJ/jsautocfg.h dependency dropped.
rm -f Darwin_DBG.OBJ/jsautocfg.h
Darwin_DBG.OBJ/jscpucfg > Darwin_DBG.OBJ/jsautocfg.h
cc -o Darwin_DBG.OBJ/jsapi.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsapi.c
jsapi.c: In function ‘JS_ConvertArgumentsVA’:
jsapi.c:272: warning: passing argument 5 of ‘TryArgumentFormatter’ from incompatible pointer type
jsapi.c: In function ‘JS_PushArgumentsVA’:
jsapi.c:380: warning: passing argument 5 of ‘TryArgumentFormatter’ from incompatible pointer type
cc -o Darwin_DBG.OBJ/jsarena.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsarena.c
cc -o Darwin_DBG.OBJ/jsarray.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsarray.c
cc -o Darwin_DBG.OBJ/jsatom.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsatom.c
cc -o Darwin_DBG.OBJ/jsbool.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsbool.c
cc -o Darwin_DBG.OBJ/jscntxt.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jscntxt.c
cc -o Darwin_DBG.OBJ/jsdate.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsdate.c
cc -o Darwin_DBG.OBJ/jsdbgapi.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsdbgapi.c
cc -o Darwin_DBG.OBJ/jsdhash.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsdhash.c
cc -o Darwin_DBG.OBJ/jsdtoa.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsdtoa.c
cc -o Darwin_DBG.OBJ/jsemit.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsemit.c
cc -o Darwin_DBG.OBJ/jsexn.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsexn.c
cc -o Darwin_DBG.OBJ/jsfun.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsfun.c
cc -o Darwin_DBG.OBJ/jsgc.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsgc.c
cc -o Darwin_DBG.OBJ/jshash.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jshash.c
cc -o Darwin_DBG.OBJ/jsinterp.o -c -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ   jsinterp.c
cc -o Darwin_DBG.OBJ/jsinvoke.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsinvoke.c
cc -o Darwin_DBG.OBJ/jsiter.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsiter.c
cc -o Darwin_DBG.OBJ/jslock.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jslock.c
cc -o Darwin_DBG.OBJ/jslog2.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jslog2.c
cc -o Darwin_DBG.OBJ/jslong.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jslong.c
cc -o Darwin_DBG.OBJ/jsmath.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsmath.c
cc -o Darwin_DBG.OBJ/jsnum.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsnum.c
cc -o Darwin_DBG.OBJ/jsobj.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsobj.c
cc -o Darwin_DBG.OBJ/jsopcode.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsopcode.c
cc -o Darwin_DBG.OBJ/jsparse.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsparse.c
cc -o Darwin_DBG.OBJ/jsprf.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsprf.c
jsprf.c: In function ‘BuildArgArray’:
jsprf.c:644: error: incompatible types in assignment
make[1]: **\* [Darwin_DBG.OBJ/jsprf.o] Error 1
make: **\* [all] Error 2
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
extconf.rb:26:in `<<': can't convert nil into String (TypeError)
    from extconf.rb:26

Gem files will remain installed in /Library/Ruby/Gems/1.8/gems/johnson-1.1.2 for inspection.
Results logged to /Library/Ruby/Gems/1.8/gems/johnson-1.1.2/ext/spidermonkey/gem_make.out

**Comment by smparkes** [comment]
You could try my fork: http://github.com/smparkes/johnson. I build on OS X, both 32 bit and 64 bit.

**Comment by micheljansen** [comment]
I can build jbarnette/johnson just fine on Mac OS X, but have troubles with the gem as well.

Although they both claim to be 1.1.2, the source seems to be different between the gem and HEAD of the GitHub repository.

**Comment by smparkes** [comment]
Do you mean the gem from rubyforge cum gemcutter? Last I saw, that was way behind master on github. You don't want to use it, I don't think. Not only might it not build, it has a bunch of problems that master doesn't have.

You should be able to build a gem yourself with "rake gem" from master (you'll probably need some prereqs like hoe). Then you can use gem to install the gem file created.

My work has been pulled into the unstable branch of jbarnette. The goal is to release an alpha 2.0 gem before too long.

If you have build problems, feel free to post the build output in google group (groups.google.com/group/johnson-talk)

**Comment by micheljansen** [comment]
I am having troubles installing the gem from gemcutter:

```
Building native extensions.  This could take a while...
ERROR:  Error installing johnson:
    ERROR: Failed to build gem native extension.

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby extconf.rb
cat: ../../dist/Darwin_DBG.OBJ/nspr/Version: No such file or directory
cd editline; make -f Makefile.ref all
cc -o Darwin_DBG.OBJ/editline.o -c -Wall -Wno-format -MMD -DXP_UNIX -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root  -DJSFILE  -DANSI_ARROWS -DHAVE_TCGETATTR -DHIDE -DUSE_DIRENT -DSYS_UNIX -DHAVE_STDLIB -DUNIQUE_HISTORY editline.c
editline.c: In function ‘readline’:
editline.c:1038: warning: implicit declaration of function ‘getpid’
editline.c: In function ‘add_history’:
editline.c:1051: warning: pointer targets in passing argument 2 of ‘strcmp’ differ in signedness
cc -o Darwin_DBG.OBJ/sysunix.o -c -Wall -Wno-format -MMD -DXP_UNIX -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root  -DJSFILE  -DANSI_ARROWS -DHAVE_TCGETATTR -DHIDE -DUSE_DIRENT -DSYS_UNIX -DHAVE_STDLIB -DUNIQUE_HISTORY sysunix.c
ar rv Darwin_DBG.OBJ/libedit.a Darwin_DBG.OBJ/editline.o Darwin_DBG.OBJ/sysunix.o
r - Darwin_DBG.OBJ/editline.o
r - Darwin_DBG.OBJ/sysunix.o
```

...
    jsprf.c: In function ‘BuildArgArray’:
    jsprf.c:644: error: incompatible types in assignment
    make[1]: **\* [Darwin_DBG.OBJ/jsprf.o] Error 1
    make: **\* [all] Error 2
    **\* extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of
    necessary libraries and/or headers.  Check the mkmf.log file for more
    details.  You may need configuration options.

```
Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
extconf.rb:26:in `<<': can't convert nil into String (TypeError)
    from extconf.rb:26


Gem files will remain installed in /Library/Ruby/Gems/1.8/gems/johnson-1.1.2 for inspection.
Results logged to /Library/Ruby/Gems/1.8/gems/johnson-1.1.2/ext/spidermonkey/gem_make.out
```

The one I checked out from jbarnette/johnson (master) built just fine: "rake gem" works nicely.

**Comment by smparkes** [comment]
Yeah. We should probalby make a new release from master as well as working on the 2.0 stuff.

**Comment by chrislloyd** [comment]
+1 For having a gem that we can install.

**Comment by jbarnette** [comment]
Fixed in the 1.2.0 release!
